If:
  PathMatch: .*\.cpp
CompileFlags:
    Add: [-std=c++26]
---

If:
  PathMatch: .*\.hpp
CompileFlags:
    Add: [-std=c++26]
---

If:
  PathMatch: .*\.c
CompileFlags:
    Add: [-std=c17]

---

CompileFlags:
  CompilationDatabase: build

Diagnostics:
  ClangTidy:
    UseBuildDir: Yes
