[buildPlans.iosevkaHe7086]
family = "Iosevka HE7086"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.iosevkaHe7086.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing"
f = "flat-hook-serifless"
l = "tailed-serifed"
r = "compact-serifed"
one = "base"
two = "straight-neck-serifless"
asterisk = "penta-low"
caret = "low"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"

[buildPlans.iosevkaHe7086.variants.italic]
f = "flat-hook-tailed"

[buildPlans.iosevkaHe7086.ligations]
enables = [ "arrow"
          , "center-ops"
          , "ltgt-diamond"
          , "brst"
          , "html-comment"
          ]

[buildPlans.iosevkaHe7086.excludeChars]
ranges = [[0x2639, 0x263a]]
# ☹ ☺ 

[collectPlans.iosevkaHe7086]
from = ["iosevkaHe7086"]

# The quick brown fox jumps over the lazy dog
