[manager]
prepend_keymap = [
    { on = [ "l" ], exec = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
    { on = [ "q" ], exec = "quit --no-cwd-file",        desc = "Exit the process without writing cwd-file" },
    { on = [ "Q" ], exec = "quit",                      desc = "Exit the process" }
]
