[manager]
prepend_keymap = [
    { on = [ "l" ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = [ "L" ], run = "plugin sudoedit",    desc = "Edit the file with sudoedit" },

    { on = [ "q" ], run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
    { on = [ "Q" ], run = "quit",               desc = "Exit the process" },

    { on = [ "d", "d" ], run = "remove --force",               desc = "Move files to trash" },
    { on = [ "d", "D" ], run = "remove --force --permanently", desc = "Delete files" },

    { on = [ "@" ], run = 'shell --block --interactive --cursor=0 " $@"', desc = "Run a shell command" },

    { on = [ "<Up>" ],    run = "seek -1", desc = "Scroll up the preview panel" },
    { on = [ "<Down>" ],  run = "seek 1",  desc = "Scroll down the preview panel" },
    # { on = [ "<Left>" ],  run = "seek -1", desc = "Scroll up the preview panel" },
    # { on = [ "<Right>" ], run = "seek 1",  desc = "Scroll down the preview panel" },
]
