[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

mode_normal = { fg = "white", bg = "blue" }
mode_select = { fg = "white", bg = "red" }
# mode_unset = ""

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "cyan" },

    # Videos
    { mime = "video/*", fg = "yellow" },
    { mime = "audio/*", fg = "yellow" },

    # Archives
    { mime = "application/zip",             fg = "magenta" },
    { mime = "application/gzip",            fg = "magenta" },
    { mime = "application/tar",             fg = "magenta" },
    { mime = "application/bzip",            fg = "magenta" },
    { mime = "application/bzip2",           fg = "magenta" },
    { mime = "application/7z-compressed",   fg = "magenta" },
    { mime = "application/rar",             fg = "magenta" },
    { mime = "application/xz",              fg = "magenta" },
    { mime = "application/zstd",            fg = "magenta" },

    # Documents
    { mime = "application/doc",   fg = "green" },
    { mime = "application/pdf",   fg = "green" },
    { mime = "application/rtf",   fg = "green" },
    { mime = "application/vnd.*", fg = "green" },

    { name = "*", is = "block",  fg = "yellow" },
    { name = "*", is = "char",   fg = "yellow" },
    { name = "*", is = "fifo",   fg = "yellow" },
    { name = "*", is = "sock",   fg = "yellow" },
    { name = "*", is = "orphan", fg = "magenta" },
    { name = "*", is = "link",   fg = "cyan" },
    { name = "*/", is = "link",   fg = "cyan" },

    { name = "*/", fg = "blue" },

    { name = "*", is = "exec", fg = "green" },
]
