# switch to bash temporarily
if [[ "$TTY" = "/dev/tty2" ]]; then
    exec bash
fi

# auto install for first time
if [[ ! -e $ZSH/oh-my-zsh.sh ]]; then
    curl -Lo ~/omz_install.sh https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    chmod +x ~/omz_install.sh
    ~/omz_install.sh --unattended
    export ZSH_CUSTOM="$HOME/.config/oh-my-zsh/custom"
    git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM}/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
    git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM}/plugins/zsh-history-substring-search
    rm -f ~/omz_install.sh
    rm -f ~/.zshrc
    mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc # XDG_CONFIG_HOME
    # chsh -s /usr/bin/zsh
fi

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/zsh_history

# ignore duplicates in the history
setopt HIST_IGNORE_ALL_DUPS

autoload -U colors && colors

autoload -U compinit 
zstyle ':completion:*' menu select
zmodload zsh/complist

#------------------------------------------------
# other settings
#------------------------------------------------
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"
# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

source $ZDOTDIR/zshfunc
source $ZDOTDIR/zshkeys
source $ZDOTDIR/zshplugin

# make sure to source this one at last
source $ZSH/oh-my-zsh.sh

compinit
# completion including hidden files
_comp_options+=(globdots)

#------------------------------------------------
# Aliases
#------------------------------------------------
alias vim='nvim'
alias vi='nvim'
alias ra='ranger'
alias nf='neofetch'
alias py='python3'
alias rf='rifle'
alias sctl='sudo systemctl '
alias sl='ls'

# make sure to leave a space at the end to enable appended aliases
alias sudo='sudo '
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval $(thefuck --alias)
