name: "Update Submodules"
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: "[Auto] Update Submodules"
          commit_user_name: HE7086
          commit_user_email: me@heyi7086.com
          commit_author: HE7086 <me@heyi7086.com>
